# Generated by Django 4.1.4 on 2022-12-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='price',
        ),
        migrations.AddField(
            model_name='house',
            name='pets_allowed',
            field=models.BooleanField(default=True, help_text='Does this house allow pets?', verbose_name='Pets Allowed?'),
        ),
        migrations.AddField(
            model_name='house',
            name='price_per_night',
            field=models.PositiveIntegerField(default=True, help_text='Positive Numbers Only', verbose_name='Price'),
        ),
    ]
