# Generated by Django 4.1.4 on 2023-08-12 06:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "experiences",
            "0003_alter_experience_category_alter_experience_host_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="end",
            new_name="event_end",
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="start",
            new_name="event_start",
        ),
        migrations.RemoveField(
            model_name="perk",
            name="explanation",
        ),
        migrations.AddField(
            model_name="experience",
            name="event_duration",
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
        migrations.AddField(
            model_name="perk",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="city",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="experience",
            name="country",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="experience",
            name="host",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="experiences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="perk",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
