# Generated by Django 4.1.4 on 2023-08-12 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0004_rename_end_experience_event_end_and_more"),
        ("medias", "0002_alter_photo_experience_alter_photo_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="is_thumbnail",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="video",
            name="description",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="video",
            name="experience",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="experiences.experience",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.URLField(),
        ),
    ]
