# Generated by Django 4.1.4 on 2023-08-12 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_host_approval_state_booking_is_cancelled"),
        ("reviews", "0002_alter_review_experience_alter_review_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="booking",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review",
                to="bookings.booking",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="payload",
            field=models.TextField(blank=True, null=True),
        ),
    ]
