# Generated by Django 4.1.4 on 2023-08-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0004_rename_end_experience_event_end_and_more"),
        ("rooms", "0004_remove_room_pet_friendly_alter_amenity_name_and_more"),
        ("wishlists", "0002_alter_wishlist_experiences_alter_wishlist_rooms_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wishlist",
            old_name="user",
            new_name="owner",
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="experiences",
            field=models.ManyToManyField(
                blank=True, related_name="wishlists", to="experiences.experience"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="rooms",
            field=models.ManyToManyField(
                blank=True, related_name="wishlists", to="rooms.room"
            ),
        ),
    ]
